# -*- coding: utf-8 -*-
"""Lista1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pyiVVeV6SaXuDVuvWk2p6mgBdccSN07d

# Primeira Lista de Exercícios valendo ponto
## - Ambiente Colab
## - Variáveis
## - Recebendo inputs do usuário

## Questão 1
Escreva uma célula de texto com o seu nome.
"""

Nome="Felipe de Jesus"

"""#Questão 2
Faça um programa que mostre seu nome completo na tela.
"""

print(Nome)

"""#Questão 3
Faça um programa que peça um número e então mostre a mensagem: O número informado foi [número].
"""

numero= 123456
print("O número informado foi", numero)

"""#Questão 4
Faça um programa que peça as 4 notas bimestrais e mostre a média.
"""

Nota1 = float(input("Primeira nota"))
Nota2 = float(input("Segunda nota"))
Nota3 = float(input("Terceira nota"))
Nota4 = float(input("Quarta nota"))
MediaNota = (Nota1+Nota2+Nota3+Nota4)/4
print("A média é",MediaNota)

"""#Questão 5
Faça um programa para uma loja de tintas. O programa deverá pedir o tamanho em metros quadrados da área a ser
pintada. Considere que a cobertura da tinta é de 1 litro para cada 3 metros quadrados e que a tinta é vendida em latas
de 18 litros, que custam R$ 80,00. Informe ao usuário a quantidades de latas de tinta a serem compradas e o preço
total.
"""

area = float(input("Digite o valor da area a ser pintada: "))
LataTinta=  area * 3
Latas = LataTinta / 18
preco = Latas * 80
print(Latas)
print(preco)

"""#Questão 6
Faça um programa para um mercadinho de bairro. O programa deverá perguntar quantas bananas, uvas e maças o cliente deseja comprar e então mostrar o valor da compra. Cada banana custa R\$1,00, cada uva custa R\$2,50 e cada maça custa R\$1,35.
"""

Banana = 1
Uva = 2.50
Maça = 1.35
qtd_banana = int(input("quantas bananas deseja comprar? "))
qtd_uva = int(input("Quantas uvas você deseja comprar? "))
qtd_maca = int(input("Quantas maçãs você deseja comprar? "))

TotalBanana= Banana * qtd_banana
TotalUva= Uva * qtd_uva
TotalMaça= Maça * qtd_maca
ValorCompra= TotalBanana + TotalUva + TotalMaça
print(ValorCompra)

"""#Questão 7
João Papo-de-Pescador, homem de bem, comprou um microcomputador para controlar o rendimento diário de seu
trabalho. Toda vez que ele traz um peso de peixes maior que o estabelecido pelo regulamento de pesca do estado de
São Paulo (50 quilos) deve pagar uma multa de R$ 4,00 por quilo excedente. João precisa que você faça um
programa que leia a variável peso (peso de peixes) e calcule o excesso. Gravar na variável excesso a quantidade de
quilos além do limite e na variável multa o valor da multa que João deverá pagar. Imprima os dados do programa com
as mensagens adequadas.
"""

peso = float(input("Digite o peso dos peixes (em quilos): "))
limite = 50

if peso > limite:
    excesso = peso - limite
    multa = excesso * 4
    print(f"O excesso de peso é {excesso} kg.")
    print(f"A multa que João deverá pagar é R$" + str(multa))
else:
    print("Não há excesso de peso. Não há multa a pagar.")

"""#Questão 8
Faça um programa que solicita do usuário a cidade onde ele mora e o seu nome e então imprime a mensagem: [nome] mora na cidade [cidade].
"""

print("Qual seu nome?")
Nome= str(input())
print("Qual cidade você mora?")
Cidade= str(input())
print(Nome, "mora na cidade", Cidade)

"""#Questão 9
Defina uma váriavel com o seguinte código:


```
numero = "5"
```
Imprima o valor da variável e o seu tipo. Observe que essa variável apesar de ser mostrada como um número no print, o python a trata como string.


"""

numero = "5"
print("Valor da variavel: ", numero)
print("Tipo da variável: ", type(numero))

"""#Questão 10
Tente utilizar a variável declarada na questão nove para exibir sua soma com a variável


```
outroNumero = 10
```

Observe o erro ocorrido e a importância de entender sobre os tipos de variável.

"""

numero = "5"
outroNumero = 10
print(int(numero) + outroNumero)